# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maven_demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: qyf
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
     port: 8081
     tomcat:
        max-threads: 1000
        min-spare-threads: 30